create database bd_sesc;

use bd_sesc;

create table Usuario(
idt_cpf int auto_increment primary key,
nome varchar(100) not null,
dtNascimento varchar(100) not null,
sexo varchar(1) not null,
stCivil varchar(20) not null,
cep int not null,
endereco varchar(50) not null,
complemento varchar(50) not null,
bairro varchar(50) not null,
UF varchar(50) not null,
cidade varchar(50) not null,
habilitacao varchar(1) not null,
nomePai varchar(100) not null,
nomeMae varchar(100) not null,
RG int not null,
orgEmissor varchar(10) not null,
naturalidade varchar(20) not null,
nacionalidade varchar(20) not null,
profissao varchar(50) not null,
renda int not null,
grauInstru varchar(10) not null,
telCelular int not null,
telResidencial int not null,
telComercial int not null,
email varchar(100) not null,
senha varchar(100) not null
);

create table Dependente(
idt_cpf int auto_increment primary key,
nome varchar(100) not null,
dtNascimento varchar(20) not null,
sexo varchar(1) not null,
stCivil varchar(20) not null,
cep int not null,
endereco varchar(50) not null,
complemento varchar(50) not null,
bairro varchar(50) not null,
UF varchar(50) not null,
cidade varchar(50) not null,
habilitacao varchar(1) not null,
nomePai varchar(100) not null,
nomeMae varchar(100) not null,
RG int not null,
orgEmissor varchar(10) not null,
naturalidade varchar(20) not null,
nacionalidade varchar(20) not null,
profissao varchar(50) not null,
renda int not null,
grauInstru varchar(10) not null,
telCelular int not null,
telResidencial int not null,
telComercial int not null,
email varchar(100) not null,
senha varchar(100) not null,
parentesco varchar(50) not null
);


create table Comerciario(
idt_cpf int auto_increment primary key,
nome varchar(100) not null,
dtNascimento varchar(20) not null,
sexo varchar(1) not null,
stCivil varchar(20) not null,
cep int not null,
endereco varchar(50) not null,
complemento varchar(50) not null,
bairro varchar(50) not null,
UF varchar(50) not null,
cidade varchar(50) not null,
habilitacao varchar(1) not null,
nomePai varchar(100) not null,
nomeMae varchar(100) not null,
RG int not null,
orgEmissor varchar(10) not null,
naturalidade varchar(20) not null,
nacionalidade varchar(20) not null,
profissao varchar(50) not null,
renda int not null,
grauInstru varchar(10) not null,
telCelular int not null,
telResidencial int not null,
telComercial int not null,
email varchar(100) not null,
senha varchar(100) not null,
nCarteira long not null,
cnpj long not null,
dtAdmissao varchar(20) not null,
habitacao varchar(50) not null
);

